const PDFDocument = require('pdfkit');

// ─── Traductions ────────────────────────────────────────────────────────────
const LABELS = {
  en: {
    title: 'MONITORING & VERIFICATION REPORT',
    subtitle: 'Annual Monitoring, Reporting & Verification Report',
    project: 'Project',
    country: 'Country',
    installed: 'installed',
    monitoringPeriod: 'Monitoring Period',
    methodology: 'Methodology',
    standard: 'Standard',
    reportDate: 'Report Date',
    keyResults: 'KEY RESULTS',
    totalProduction: 'Total Production',
    grossReductions: 'Gross Emission Reductions',
    netCredits: 'Net Carbon Credits',
    estimatedRevenue: 'Estimated Carbon Revenue',
    technicalAnalysis: 'TECHNICAL ANALYSIS',
    emissionFactor: 'Grid Emission Factor',
    leakage: 'Leakage Deduction (3%)',
    uncertainty: 'Uncertainty Deduction (5%)',
    monthlyData: 'MONTHLY PRODUCTION DATA',
    month: 'Month', production: 'Production (MWh)', peakPower: 'Peak Power (MW)',
    availability: 'Availability (%)', status: 'Status', verified: 'Verified',
    financials: 'FINANCIAL VALUATION',
    creditsLabel: 'Net Carbon Credits',
    priceLabel: 'Market Price',
    grossRevenue: 'Gross Revenue',
    verificationCost: 'Verification Costs (8%)',
    netRevenue: 'ESTIMATED NET REVENUE',
    equivalents: 'ENVIRONMENTAL EQUIVALENTS',
    cars: '🚗 Cars removed from roads',
    trees: '🌳 Equivalent trees planted',
    homes: '🏠 African homes electrified',
    declaration: 'COMPLIANCE DECLARATION',
    preparedBy: 'Prepared by',
    approvedBy: 'Approved by',
    vvbLabel: 'Validation and Verification Body\nTo be completed by accredited VVB',
    footerNote: 'This report is automatically generated by the PANGEA CARBON platform. It must be submitted to a Verra/Gold Standard accredited VVB auditor for validation and carbon credit issuance.',
  },
  fr: {
    title: 'RAPPORT DE MONITORING & VÉRIFICATION',
    subtitle: 'Rapport annuel de Monitoring, Reporting & Vérification',
    project: 'Projet',
    country: 'Pays',
    installed: 'installés',
    monitoringPeriod: 'Période de monitoring',
    methodology: 'Méthodologie',
    standard: 'Standard',
    reportDate: 'Date du rapport',
    keyResults: 'RÉSULTATS CLÉS',
    totalProduction: 'Production totale',
    grossReductions: "Réductions d'émissions brutes",
    netCredits: 'Crédits carbone nets',
    estimatedRevenue: 'Revenus carbone estimés',
    technicalAnalysis: 'ANALYSE TECHNIQUE',
    emissionFactor: "Facteur d'émission réseau",
    leakage: 'Déduction leakage (3%)',
    uncertainty: 'Déduction incertitude (5%)',
    monthlyData: 'DONNÉES DE PRODUCTION MENSUELLES',
    month: 'Mois', production: 'Production (MWh)', peakPower: 'Puissance crête (MW)',
    availability: 'Disponibilité (%)', status: 'Statut', verified: 'Vérifié',
    financials: 'VALORISATION FINANCIÈRE',
    creditsLabel: 'Crédits carbone nets',
    priceLabel: 'Prix de marché',
    grossRevenue: 'Revenus bruts',
    verificationCost: 'Coûts vérification (8%)',
    netRevenue: 'REVENUS NETS ESTIMÉS',
    equivalents: 'ÉQUIVALENTS ENVIRONNEMENTAUX',
    cars: '🚗 Voitures retirées de la route',
    trees: '🌳 Arbres équivalents plantés',
    homes: '🏠 Foyers africains électrifiés',
    declaration: 'DÉCLARATION DE CONFORMITÉ',
    preparedBy: 'Préparé par',
    approvedBy: 'Approuvé par',
    vvbLabel: "Validation et Vérification Body\nÀ compléter par auditeur VVB",
    footerNote: "Ce rapport est généré automatiquement par la plateforme PANGEA CARBON. Il doit être soumis à un auditeur VVB accrédité Verra/Gold Standard pour validation et issuance des crédits carbone.",
  },
};

// ─── Config par standard ─────────────────────────────────────────────────────
const STANDARD_CONFIG = {
  VERRA_VCS: {
    name: 'Verra Verified Carbon Standard (VCS)',
    method: 'ACM0002 v19.0 — Consolidated methodology for grid-connected RE',
    creditName: { en: 'VCUs (Verified Carbon Units)', fr: 'VCUs (Unités Carbone Vérifiées)' },
    registry: 'Verra Registry',
    accentColor: '#00875A',
    priceUSD: 11.04,
  },
  GOLD_STANDARD: {
    name: 'Gold Standard for the Global Goals (GS4GG)',
    method: 'CDM LCB + GS4GG methodology',
    creditName: { en: 'GSCERs (Gold Standard Certified Emission Reductions)', fr: "GSCERs (Réductions d'Émissions Certifiées Gold Standard)" },
    registry: 'Gold Standard Registry',
    accentColor: '#D97706',
    priceUSD: 18.50,
  },
  ARTICLE6: {
    name: 'Paris Agreement Article 6 — ITMO',
    method: 'A6.4ER — Article 6.4 Mechanism',
    creditName: { en: 'ITMOs (Internationally Transferred Mitigation Outcomes)', fr: "ITMOs (Résultats d'Atténuation Transférés Internationalement)" },
    registry: 'UNFCCC Article 6.4 Registry',
    accentColor: '#2563EB',
    priceUSD: 25.00,
  },
  CDM: {
    name: 'Clean Development Mechanism (CDM) — UNFCCC',
    method: 'CDM methodology — CER generation',
    creditName: { en: 'CERs (Certified Emission Reductions)', fr: "CERs (Réductions d'Émissions Certifiées)" },
    registry: 'UNFCCC CDM Registry',
    accentColor: '#6B7280',
    priceUSD: 3.50,
  },
  ACR: {
    name: 'American Carbon Registry (ACR)',
    method: 'ACR Renewable Energy methodology v1.0',
    creditName: { en: 'ERTs (Emission Reduction Tonnes)', fr: "ERTs (Tonnes de Réduction d'Émissions)" },
    registry: 'ACR Registry — Winrock International',
    accentColor: '#DC2626',
    priceUSD: 10.00,
  },
  CAR: {
    name: 'Climate Action Reserve (CAR)',
    method: 'CAR Renewable Energy methodology',
    creditName: { en: 'CRTs (Climate Reserve Tonnes)', fr: 'CRTs (Tonnes Réserve Climatique)' },
    registry: 'Climate Action Reserve Registry',
    accentColor: '#059669',
    priceUSD: 9.50,
  },
  CORSIA: {
    name: 'CORSIA — Carbon Offsetting Scheme for International Aviation',
    method: 'CORSIA-eligible units — ICAO methodology',
    creditName: { en: 'CORSIA Eligible Units (CEUs)', fr: 'Unités Éligibles CORSIA (CEUs)' },
    registry: 'ICAO CORSIA Central Registry',
    accentColor: '#7C3AED',
    priceUSD: 15.00,
  },
  VCMI: {
    name: 'VCMI Claims Code of Practice — CCP Label',
    method: 'ICVCM Core Carbon Principles (CCP) v2.0',
    creditName: { en: 'CCP-labelled credits (ICVCM)', fr: "Crédits labellisés CCP (ICVCM)" },
    registry: 'ICVCM-approved registry',
    accentColor: '#0891B2',
    priceUSD: 20.00,
  },
  PLAN_VIVO: {
    name: 'Plan Vivo Standard',
    method: 'Plan Vivo — Community-based carbon methodology',
    creditName: { en: 'Plan Vivo Certificates (PVCs)', fr: 'Certificats Plan Vivo (PVCs)' },
    registry: 'Plan Vivo Registry',
    accentColor: '#65A30D',
    priceUSD: 14.00,
  },
};

/**
 * Génère un rapport MRV certifiable pour le standard et la langue choisis
 * @param {Object} project
 * @param {Object} mrvData
 * @param {Array}  readings
 * @param {string} lang     — 'en' | 'fr'
 * @param {string} standardId — VERRA_VCS | GOLD_STANDARD | ARTICLE6 | CDM | ACR | CAR | CORSIA | VCMI | PLAN_VIVO
 */
async function generateMRVReport(project, mrvData, readings, lang = 'fr', standardId = 'VERRA_VCS') {
  return new Promise((resolve, reject) => {
    const T = LABELS[lang] || LABELS.fr;
    const STD = STANDARD_CONFIG[standardId] || STANDARD_CONFIG.VERRA_VCS;
    const creditName = STD.creditName[lang] || STD.creditName.fr;
    const accentColor = STD.accentColor;

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const C = {
      black: '#0A0A0A', dark: '#1A1A2E',
      green: accentColor, lightGreen: '#E3FCF3',
      gray: '#6B7280', lightGray: '#F3F4F6',
      border: '#E5E7EB', accent: accentColor, white: '#FFFFFF',
    };

    const locale = lang === 'fr' ? 'fr-FR' : 'en-US';
    const fmt = (n, d = 0) => n ? Number(n).toLocaleString(locale, { minimumFractionDigits: d, maximumFractionDigits: d }) : '—';
    const now = new Date();
    const reportId = 'PGC-' + (standardId.slice(0,3)) + '-' + (project.countryCode||'AF') + '-' + mrvData.year + '-' + Date.now().toString(36).toUpperCase();

    // ── COVER PAGE ─────────────────────────────────────────────────────────
    doc.rect(0, 0, 595, 200).fill(C.dark);
    doc.rect(0, 200, 595, 4).fill(C.green);

    doc.font('Helvetica-Bold').fontSize(28).fillColor(C.white).text('PANGEA CARBON', 50, 55);
    doc.font('Helvetica').fontSize(11).fillColor('#9CA3AF').text('Carbon Credit Intelligence · Africa', 50, 90);

    doc.font('Helvetica-Bold').fontSize(16).fillColor(C.white).text(T.title, 50, 125);
    doc.font('Helvetica').fontSize(10).fillColor('#9CA3AF').text(T.subtitle, 50, 148);

    // Standard badge
    doc.rect(390, 50, 155, 30).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(8).fillColor(C.white).text(standardId.replace('_',' '), 398, 57);
    doc.font('Helvetica').fontSize(7).fillColor(C.white).text(lang.toUpperCase() + ' VERSION', 398, 68);

    // Report ID
    doc.rect(390, 88, 155, 20).fill('#0D1117');
    doc.font('Helvetica-Bold').fontSize(7).fillColor(accentColor).text(reportId, 398, 94);

    // Project info block
    doc.rect(50, 220, 495, 115).fill(C.lightGray).stroke(C.border);
    doc.font('Helvetica-Bold').fontSize(15).fillColor(C.dark).text(project.name, 65, 235);
    doc.font('Helvetica').fontSize(10).fillColor(C.gray)
       .text((project.type||'') + ' · ' + (project.country||'') + ' · ' + (project.installedMW||'—') + ' MW ' + T.installed, 65, 255);

    const dateFmt = now.toLocaleDateString(locale, { year:'numeric', month:'long', day:'numeric' });
    const meta = [
      [T.monitoringPeriod, '01/01/' + mrvData.year + ' – 31/12/' + mrvData.year],
      [T.methodology, STD.method],
      [T.standard, STD.name],
      [T.reportDate, dateFmt],
    ];
    meta.forEach(([k, v], i) => {
      doc.font('Helvetica-Bold').fontSize(9).fillColor(C.gray).text(k, 65, 280 + i * 13);
      doc.font('Helvetica').fontSize(9).fillColor(C.dark).text(v, 220, 280 + i * 13);
    });

    // ── KEY RESULTS ─────────────────────────────────────────────────────────
    const kpiY = 355;
    doc.rect(50, kpiY, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.keyResults, 50, kpiY + 10);

    const price = STD.priceUSD;
    const netCredits = mrvData.emissions?.netCarbonCredits || mrvData.netCarbonCredits || 0;
    const netRevenue = (netCredits * price * 0.92).toFixed(0);
    const grossRevenue = (netCredits * price).toFixed(0);

    const kpis = [
      [T.totalProduction, fmt(mrvData.projectMetrics?.totalMWh || mrvData.grossEnergy) + ' MWh', C.dark],
      [T.grossReductions, fmt(mrvData.emissions?.grossReductions || mrvData.grossReductions) + ' tCO₂e', C.dark],
      [T.netCredits + ' (' + creditName.split(' ')[0] + ')', fmt(netCredits) + ' tCO₂e', C.green],
      [T.estimatedRevenue + ' @ $' + price + '/t', '$' + fmt(Number(netRevenue)), C.accent],
    ];

    let kY = kpiY + 30;
    kpis.forEach(([k, v, col], i) => {
      const isHighlight = i >= 2;
      doc.rect(50, kY, 495, isHighlight ? 26 : 20).fill(isHighlight ? C.lightGreen : i % 2 === 0 ? C.lightGray : C.white).stroke(C.border);
      doc.font(isHighlight ? 'Helvetica-Bold' : 'Helvetica').fontSize(isHighlight ? 10 : 9)
         .fillColor(isHighlight ? C.green : C.dark).text(k, 60, kY + (isHighlight ? 8 : 6));
      doc.font('Helvetica-Bold').fontSize(isHighlight ? 11 : 9)
         .fillColor(col).text(v, 400, kY + (isHighlight ? 8 : 6), { align: 'right', width: 135 });
      kY += isHighlight ? 26 : 20;
    });

    // ── TECHNICAL SECTION ───────────────────────────────────────────────────
    kY += 20;
    doc.rect(50, kY, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.technicalAnalysis, 50, kY + 10);
    kY += 28;

    const ef = mrvData.gridEmissionFactor || mrvData.emissions?.emissionFactor || 0;
    const gross = mrvData.emissions?.grossReductions || mrvData.grossReductions || 0;
    const leak = gross * 0.03;
    const unc = gross * 0.05;

    const techRows = [
      [T.emissionFactor, ef.toFixed(3) + ' tCO₂/MWh'],
      [T.leakage, '− ' + fmt(leak, 1) + ' tCO₂e'],
      [T.uncertainty, '− ' + fmt(unc, 1) + ' tCO₂e'],
      [T.netCredits, fmt(netCredits) + ' tCO₂e → ' + creditName.split(' ')[0]],
    ];
    techRows.forEach(([k, v], i) => {
      doc.rect(50, kY, 495, 18).fill(i % 2 === 0 ? C.lightGray : C.white).stroke(C.border);
      doc.font('Helvetica').fontSize(9).fillColor(C.dark).text(k, 60, kY + 5);
      doc.font('Helvetica-Bold').fontSize(9).fillColor(C.accent).text(v, 400, kY + 5, { align: 'right', width: 135 });
      kY += 18;
    });

    // ── PAGE 2 — MONTHLY DATA ───────────────────────────────────────────────
    doc.addPage();
    doc.rect(0, 0, 595, 40).fill(C.dark);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(C.white).text('PANGEA CARBON · ' + T.monthlyData, 50, 14);
    doc.font('Helvetica').fontSize(8).fillColor('#9CA3AF').text(reportId, 420, 22);

    doc.rect(50, 55, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.monthlyData, 50, 67);

    let tY = 90;
    const headers = [T.month, T.production, T.peakPower, T.availability, T.status];
    const colX = [60, 140, 260, 380, 470];
    doc.rect(50, tY, 495, 18).fill(C.dark);
    headers.forEach((h, i) => {
      doc.font('Helvetica-Bold').fontSize(8).fillColor(C.white).text(h, colX[i], tY + 5, { width: 110, lineBreak: false });
    });
    tY += 18;

    (readings || []).slice(0, 12).forEach((r, i) => {
      const bg = i % 2 === 0 ? C.white : C.lightGray;
      doc.rect(50, tY, 495, 16).fill(bg).stroke(C.border);
      const monthStr = new Date(r.periodStart).toLocaleDateString(locale, { month: 'long', year: 'numeric' });
      [monthStr, fmt(r.energyMWh, 1), fmt(r.peakPowerMW, 1), r.availabilityPct ? fmt(r.availabilityPct, 1) : '—', T.verified].forEach((v, ci) => {
        doc.font('Helvetica').fontSize(8).fillColor(C.dark).text(String(v), colX[ci], tY + 4, { width: 110, lineBreak: false });
      });
      tY += 16;
    });

    // ── PAGE 3 — FINANCIALS + CERTIFICATION ─────────────────────────────────
    doc.addPage();
    doc.rect(0, 0, 595, 40).fill(C.dark);
    doc.font('Helvetica-Bold').fontSize(10).fillColor(C.white).text('PANGEA CARBON · ' + T.financials, 50, 14);
    doc.font('Helvetica').fontSize(8).fillColor('#9CA3AF').text(reportId, 420, 22);

    doc.rect(50, 55, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.financials, 50, 67);

    const revRows = [
      [T.creditsLabel, fmt(netCredits) + ' tCO₂e'],
      [T.priceLabel + ' (' + STD.name.split(' ')[0] + ')', '$' + price + '/tCO₂e'],
      [T.grossRevenue, '$' + fmt(Number(grossRevenue))],
      [T.verificationCost, '− $' + fmt(Number(grossRevenue) * 0.08)],
      [T.netRevenue, '$' + fmt(Number(netRevenue))],
    ];

    let rY = 90;
    revRows.forEach(([k, v], i) => {
      const isTotal = i === revRows.length - 1;
      doc.rect(50, rY, 495, isTotal ? 26 : 20).fill(isTotal ? C.lightGreen : i % 2 === 0 ? C.lightGray : C.white).stroke(C.border);
      doc.font(isTotal ? 'Helvetica-Bold' : 'Helvetica').fontSize(isTotal ? 11 : 9)
         .fillColor(isTotal ? C.green : C.dark).text(k, 60, rY + (isTotal ? 8 : 6));
      doc.font(isTotal ? 'Helvetica-Bold' : 'Helvetica').fontSize(isTotal ? 11 : 9)
         .fillColor(isTotal ? C.green : C.dark).text(v, 400, rY + (isTotal ? 8 : 6), { align: 'right', width: 135 });
      rY += isTotal ? 26 : 20;
    });

    rY += 20;
    doc.rect(50, rY, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.equivalents, 50, rY + 10);
    rY += 28;

    const eqs = [
      [T.cars, fmt((netCredits / 4.6).toFixed(0))],
      [T.trees, fmt((netCredits * 16.5).toFixed(0))],
      [T.homes, fmt((netCredits / 1.2).toFixed(0))],
    ];
    eqs.forEach(([label, value]) => {
      doc.rect(50, rY, 495, 22).fill(C.lightGray).stroke(C.border);
      doc.font('Helvetica').fontSize(10).fillColor(C.dark).text(label, 60, rY + 6);
      doc.font('Helvetica-Bold').fontSize(10).fillColor(C.accent).text(value, 400, rY + 6, { align: 'right', width: 135 });
      rY += 22;
    });

    // Registry + Compliance
    rY += 20;
    doc.rect(50, rY, 495, 2).fill(C.green);
    doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(T.declaration, 50, rY + 10);
    rY += 28;

    const declarationText = lang === 'fr'
      ? "Le présent rapport de Monitoring, Reporting et Vérification (MRV) a été généré conformément à la méthodologie " + STD.method + ". Les calculs de réductions d'émissions ont été effectués selon les paramètres définis dans le Plan de Surveillance approuvé. Registre: " + STD.registry + "."
      : 'This Monitoring, Reporting and Verification (MRV) report has been generated in accordance with ' + STD.method + '. Emission reduction calculations were performed according to the parameters defined in the approved Monitoring Plan. Registry: ' + STD.registry + '.';

    doc.font('Helvetica').fontSize(9).fillColor(C.gray).text(declarationText, 50, rY, { width: 495, align: 'justify' });
    rY += 60;

    [[T.preparedBy, 'PANGEA CARBON Africa\nCertified MRV Platform', 50],
     [T.approvedBy, T.vvbLabel, 290]].forEach(([role, name, x]) => {
      doc.rect(x, rY, 220, 60).stroke(C.border);
      doc.font('Helvetica-Bold').fontSize(8).fillColor(C.gray).text(role.toUpperCase(), x + 10, rY + 8);
      doc.rect(x + 10, rY + 20, 200, 1).fill(C.border);
      doc.font('Helvetica').fontSize(9).fillColor(C.dark).text(name.replace('\\n', '\n'), x + 10, rY + 26);
      doc.font('Helvetica').fontSize(8).fillColor(C.gray).text(now.toLocaleDateString(locale), x + 10, rY + 46);
    });

    // Footer
    doc.rect(0, 800, 595, 42).fill(C.dark);
    doc.font('Helvetica').fontSize(8).fillColor('#9CA3AF')
       .text('PANGEA CARBON Africa · pangea-carbon.com · ' + reportId + ' · ' + dateFmt, 50, 810, { align: 'center', width: 495 });
    doc.font('Helvetica').fontSize(7).fillColor('#6B7280')
       .text(T.footerNote, 50, 823, { align: 'center', width: 495 });

    doc.end();
  });
}

module.exports = { generateMRVReport, STANDARD_CONFIG };