// ─── 56 PAYS AFRICAINS · FACTEURS D'ÉMISSION UNFCCC 2024 / IEA 2024 / IRENA 2024 ──
export const AFRICAN_COUNTRIES = [
  // AFRIQUE DE L'OUEST
  { code:'CI', name:"Côte d'Ivoire",   ef:0.547, currency:'XOF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'GH', name:'Ghana',            ef:0.342, currency:'GHS', region:'WEST',    source:'UNFCCC 2024' },
  { code:'NG', name:'Nigeria',          ef:0.430, currency:'NGN', region:'WEST',    source:'IEA 2024' },
  { code:'SN', name:'Sénégal',          ef:0.643, currency:'XOF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'ML', name:'Mali',             ef:0.598, currency:'XOF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'BF', name:'Burkina Faso',     ef:0.674, currency:'XOF', region:'WEST',    source:'IEA 2023' },
  { code:'TG', name:'Togo',             ef:0.528, currency:'XOF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'BJ', name:'Bénin',            ef:0.489, currency:'XOF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'NE', name:'Niger',            ef:0.712, currency:'XOF', region:'WEST',    source:'IEA 2023' },
  { code:'GN', name:'Guinée',           ef:0.276, currency:'GNF', region:'WEST',    source:'UNFCCC 2024' },
  { code:'LR', name:'Liberia',          ef:0.347, currency:'LRD', region:'WEST',    source:'IEA 2023' },
  { code:'SL', name:'Sierra Leone',     ef:0.321, currency:'SLL', region:'WEST',    source:'IEA 2023' },
  { code:'GM', name:'Gambie',           ef:0.618, currency:'GMD', region:'WEST',    source:'IEA 2023' },
  { code:'GW', name:'Guinée-Bissau',    ef:0.634, currency:'XOF', region:'WEST',    source:'IEA 2023' },
  { code:'CV', name:'Cap-Vert',         ef:0.391, currency:'CVE', region:'WEST',    source:'UNFCCC 2024' },
  { code:'MR', name:'Mauritanie',       ef:0.557, currency:'MRU', region:'WEST',    source:'IEA 2023' },
  // AFRIQUE CENTRALE
  { code:'CM', name:'Cameroun',         ef:0.274, currency:'XAF', region:'CENTRAL', source:'UNFCCC 2024' },
  { code:'CD', name:'RD Congo',         ef:0.046, currency:'CDF', region:'CENTRAL', source:'UNFCCC 2024' },
  { code:'CG', name:'Congo',            ef:0.186, currency:'XAF', region:'CENTRAL', source:'IEA 2023' },
  { code:'CF', name:'Centrafrique',     ef:0.092, currency:'XAF', region:'CENTRAL', source:'IEA 2023' },
  { code:'GA', name:'Gabon',            ef:0.179, currency:'XAF', region:'CENTRAL', source:'UNFCCC 2024' },
  { code:'GQ', name:'Guinée Équatoriale',ef:0.237,currency:'XAF', region:'CENTRAL', source:'IEA 2023' },
  { code:'TD', name:'Tchad',            ef:0.784, currency:'XAF', region:'CENTRAL', source:'IEA 2023' },
  { code:'BI', name:'Burundi',          ef:0.088, currency:'BIF', region:'CENTRAL', source:'IEA 2023' },
  { code:'RW', name:'Rwanda',           ef:0.432, currency:'RWF', region:'CENTRAL', source:'UNFCCC 2024' },
  { code:'ST', name:'São Tomé & Príncipe',ef:0.521,currency:'STN',region:'CENTRAL', source:'IEA 2023' },
  // AFRIQUE DE L'EST
  { code:'KE', name:'Kenya',            ef:0.162, currency:'KES', region:'EAST',    source:'UNFCCC 2024' },
  { code:'ET', name:'Éthiopie',         ef:0.031, currency:'ETB', region:'EAST',    source:'UNFCCC 2024' },
  { code:'TZ', name:'Tanzanie',         ef:0.373, currency:'TZS', region:'EAST',    source:'UNFCCC 2024' },
  { code:'UG', name:'Ouganda',          ef:0.149, currency:'UGX', region:'EAST',    source:'UNFCCC 2024' },
  { code:'MZ', name:'Mozambique',       ef:0.184, currency:'MZN', region:'EAST',    source:'UNFCCC 2024' },
  { code:'ZM', name:'Zambie',           ef:0.096, currency:'ZMW', region:'EAST',    source:'UNFCCC 2024' },
  { code:'ZW', name:'Zimbabwe',         ef:0.614, currency:'ZWL', region:'EAST',    source:'IEA 2024' },
  { code:'MW', name:'Malawi',           ef:0.287, currency:'MWK', region:'EAST',    source:'IEA 2023' },
  { code:'MG', name:'Madagascar',       ef:0.382, currency:'MGA', region:'EAST',    source:'UNFCCC 2024' },
  { code:'SO', name:'Somalie',          ef:0.681, currency:'SOS', region:'EAST',    source:'IEA 2023' },
  { code:'DJ', name:'Djibouti',         ef:0.492, currency:'DJF', region:'EAST',    source:'IEA 2023' },
  { code:'ER', name:'Érythrée',         ef:0.715, currency:'ERN', region:'EAST',    source:'IEA 2023' },
  { code:'SS', name:'Soudan du Sud',    ef:0.834, currency:'SSP', region:'EAST',    source:'IEA 2023' },
  { code:'KM', name:'Comores',          ef:0.548, currency:'KMF', region:'EAST',    source:'IEA 2023' },
  { code:'SC', name:'Seychelles',       ef:0.451, currency:'SCR', region:'EAST',    source:'IRENA 2024' },
  { code:'MU', name:'Maurice',          ef:0.619, currency:'MUR', region:'EAST',    source:'UNFCCC 2024' },
  // AFRIQUE AUSTRALE
  { code:'ZA', name:'Afrique du Sud',   ef:0.917, currency:'ZAR', region:'SOUTH',   source:'UNFCCC 2024' },
  { code:'NA', name:'Namibie',          ef:0.346, currency:'NAD', region:'SOUTH',   source:'UNFCCC 2024' },
  { code:'BW', name:'Botswana',         ef:1.036, currency:'BWP', region:'SOUTH',   source:'UNFCCC 2024' },
  { code:'LS', name:'Lesotho',          ef:0.012, currency:'LSL', region:'SOUTH',   source:'UNFCCC 2024' },
  { code:'SZ', name:'Eswatini',         ef:0.154, currency:'SZL', region:'SOUTH',   source:'IEA 2023' },
  { code:'AO', name:'Angola',           ef:0.312, currency:'AOA', region:'SOUTH',   source:'UNFCCC 2024' },
  // AFRIQUE DU NORD
  { code:'EG', name:'Égypte',           ef:0.473, currency:'EGP', region:'NORTH',   source:'UNFCCC 2024' },
  { code:'MA', name:'Maroc',            ef:0.688, currency:'MAD', region:'NORTH',   source:'UNFCCC 2024' },
  { code:'DZ', name:'Algérie',          ef:0.556, currency:'DZD', region:'NORTH',   source:'UNFCCC 2024' },
  { code:'TN', name:'Tunisie',          ef:0.467, currency:'TND', region:'NORTH',   source:'UNFCCC 2024' },
  { code:'LY', name:'Libye',            ef:0.721, currency:'LYD', region:'NORTH',   source:'IEA 2023' },
  { code:'SD', name:'Soudan',           ef:0.549, currency:'SDG', region:'NORTH',   source:'IEA 2023' },
  // OCÉAN INDIEN
  { code:'MV', name:'Maldives',         ef:0.711, currency:'MVR', region:'INDIAN',  source:'IRENA 2024' },
];
